# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40)),
                ('unit_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=8)),
                ('special_qty', models.IntegerField(db_index=True, default=0)),
                ('special_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
